# Generated by Django 3.2 on 2021-08-02 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondedepotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramprixproduitvente',
            name='prixarrondi',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Prix arrondi'),
        ),
        migrations.AlterField(
            model_name='paramprixproduitvente',
            name='prixreelle',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Prix réelle'),
        ),
        migrations.CreateModel(
            name='PanierVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_facture', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de facture')),
                ('quantitevendu', models.IntegerField(null=True, verbose_name='Quantité vendu')),
                ('montantvendu', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Montant vendu')),
                ('acheteur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Client particulier')),
                ('bb_12', models.IntegerField(default=0, null=True, verbose_name='Caiser bb de 12 prêté au client')),
                ('bb_24', models.IntegerField(default=0, null=True, verbose_name='Caiser bb de 24 prêté au client')),
                ('snb_12', models.IntegerField(default=0, null=True, verbose_name='Caiser snb de 12 prêté au client')),
                ('snb_24', models.IntegerField(default=0, null=True, verbose_name='Caiser snb de 24 prêté au client')),
                ('paniervente', models.BooleanField(default=True, null=True)),
                ('datecreation', models.DateField(auto_now_add=True, null=True)),
                ('datemodification', models.DateField(auto_now_add=True, null=True)),
                ('etat', models.BooleanField(default=False, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondedepotapp.client', verbose_name='Client régulier')),
                ('emballage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondedepotapp.totalemballage')),
                ('paramprixproduitvente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondedepotapp.paramprixproduitvente')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondedepotapp.depotstockproduit')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondedepotapp.site')),
            ],
        ),
    ]
