# Generated by Django 3.2 on 2021-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondedepotapp', '0002_auto_20210802_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='venteproduit',
            name='no_facture',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de facture'),
        ),
    ]
