# Generated by Django 3.2 on 2021-08-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondedepotapp', '0005_alter_parametreprixachatstockproduit_detailprixproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramprixproduitvente',
            name='detailprixvente',
            field=models.CharField(choices=[('Casier entier', 'Casier entier'), ('Trois-quart de casier', 'Trois-quart de casier'), ('Démi-casier', 'Démi-asier '), ('Quart de casier', 'Quart de casier')], max_length=25, null=True),
        ),
    ]
