# Generated by Django 3.2 on 2021-08-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondedepotapp', '0009_auto_20210809_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='paniervente',
            name='montantarrondi',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Montant vendu'),
        ),
    ]
