# Generated by Django 3.2 on 2021-08-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondedepotapp', '0010_paniervente_montantarrondi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paniervente',
            name='montantarrondi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant arrondi'),
        ),
        migrations.AlterField(
            model_name='paniervente',
            name='montantvendu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant vendu'),
        ),
    ]
