# Generated by Django 3.2 on 2021-08-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondedepotapp', '0011_auto_20210809_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='venteproduit',
            name='montantarrondi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant arrondi'),
        ),
        migrations.AlterField(
            model_name='paniervente',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondedepotapp.site'),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='montantvendu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant vendu'),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondedepotapp.site'),
        ),
    ]
