# Generated by Django 3.2 on 2021-08-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondedepotapp', '0012_auto_20210809_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='paniervente',
            name='casier',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
