# Generated by Django 3.2 on 2021-08-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondedepotapp', '0013_paniervente_casier'),
    ]

    operations = [
        migrations.AddField(
            model_name='venteproduit',
            name='casier',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paniervente',
            name='casier',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
