# Generated by Django 3.2.9 on 2022-03-18 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondedepotapp', '0016_produit_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panieremballage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestiondedepotapp.site'),
        ),
    ]
