# Generated by Django 3.2.9 on 2022-03-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondedepotapp', '0018_alter_panierstockproduit_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecupererFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recup_facture_bb', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de facture')),
                ('recup_facture_snb', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de facture')),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('factures', models.ManyToManyField(blank=True, related_name='Factures', to='gestiondedepotapp.DepotStockProduit', verbose_name='Numéro de facture')),
            ],
        ),
    ]
